name : ${APP_NAME}
services:
  database:
    image: mariadb:latest
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    ports:
      - "3306:3306"
    volumes:
      - database-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend
  php-web-server:
    image: php-apache-dev-env
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - backend
    depends_on:
      - database
volumes:
  database-volume:  
networks:
  backend: